import { jsPDF } from 'jspdf';
import { QuoteResult, formatCurrency, getPricingModelName } from './pricingTypes';

/**
 * Generate a professional quote PDF
 */
export const generateQuotePDF = (
  quote: QuoteResult,
  clientName: string = 'Client',
  projectName: string = 'Voiceover Project'
): void => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('VOICEOVER QUOTE', pageWidth / 2, yPos, { align: 'center' });
  
  yPos += 15;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  }), pageWidth / 2, yPos, { align: 'center' });

  // Client and Project Info
  yPos += 20;
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('Project Details', 20, yPos);
  
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Client: ${clientName}`, 20, yPos);
  
  yPos += 7;
  doc.text(`Project: ${projectName}`, 20, yPos);

  // Script Analysis
  yPos += 15;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Script Analysis', 20, yPos);
  
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Word Count: ${quote.wordCount.toLocaleString()} words`, 20, yPos);
  
  yPos += 7;
  doc.text(`Estimated Reading Time: ${quote.readingTime}`, 20, yPos);
  
  yPos += 7;
  doc.text(`Pricing Model: ${getPricingModelName(quote.pricingModel)}`, 20, yPos);

  // Pricing Breakdown
  yPos += 15;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Pricing Breakdown', 20, yPos);
  
  yPos += 10;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  
  // Base price line
  doc.text('Base Price:', 20, yPos);
  doc.text(formatCurrency(quote.basePrice), pageWidth - 20, yPos, { align: 'right' });
  
  // Minimum fee if applicable
  if (quote.includesMinimumFee) {
    yPos += 7;
    doc.setTextColor(100, 100, 100);
    doc.text(`(Minimum Session Fee: ${formatCurrency(quote.minimumFee)})`, 30, yPos);
    doc.setTextColor(0, 0, 0);
  }

  // Draw line
  yPos += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(20, yPos, pageWidth - 20, yPos);

  // Final price
  yPos += 10;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Initial Recording:', 20, yPos);
  doc.text(formatCurrency(quote.finalPrice), pageWidth - 20, yPos, { align: 'right' });

  // Revision price
  yPos += 10;
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text('Revision/Pickup Fee:', 20, yPos);
  doc.text(formatCurrency(quote.revisionPrice), pageWidth - 20, yPos, { align: 'right' });

  // Footer/Notes
  yPos += 25;
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('Notes:', 20, yPos);
  yPos += 6;
  doc.text('• Quote is valid for 30 days from the date above', 20, yPos);
  yPos += 5;
  doc.text('• Revision fee applies to changes after initial delivery', 20, yPos);
  yPos += 5;
  doc.text('• Additional fees may apply for expedited delivery or usage rights', 20, yPos);

  // Bottom footer
  const footerY = doc.internal.pageSize.getHeight() - 15;
  doc.setFontSize(8);
  doc.text('Generated by VO Tools', pageWidth / 2, footerY, { align: 'center' });

  // Save the PDF
  const filename = `VO_Quote_${projectName.replace(/[^a-z0-9]/gi, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(filename);
};
